#if !defined(_8086_CPU_H_)
#define _8086_CPU_H_

enum OP_CODE_TABLE_8086
{
  //@NOTE(Emilio): mov instructions
  MOV_RM_RM_8086,
  MOV_IMM_RM_8086,
  MOV_IMM_REG_8086,
  MOV_MEM_ACC_8086,
  MOV_ACC_MEM_8086,

  //@NOTE(Emilio): add instructions
  ADD_RM_RM_8086,
  ADD_IMM_RM_8086,
  ADD_IMM_ACC_8086,

  //@NOTE(Emilio): sub instructions
  SUB_RM_RM_8086,
  SUB_IMM_RM_8086,
  SUB_IMM_ACC_8086,

  //@NOTE(Emilio): cmp instructions
  CMP_RM_RM_8086,
  CMP_IMM_RM_8086,
  CMP_IMM_ACC_8086,


  OP_CODE_TABLE_8086_SIZE
};

enum REG_TABLE_8086
{
  REG_AL_8086,
  REG_CL_8086,
  REG_DL_8086,
  REG_BL_8086,
  REG_AH_8086,
  REG_CH_8086,
  REG_DH_8086,
  REG_BH_8086,

  //@NOTE(Emilio): (REG % 8) + 8
  REG_AX_8086,
  REG_CX_8086,
  REG_DX_8086,
  REG_BX_8086,
  REG_SP_8086,
  REG_BP_8086,
  REG_SI_8086,
  REG_DI_8086,

  REG_TABLE_8086_SIZE
};

enum RM_TABLE_8086
{
  RM_BX_SI_8086,
  RM_BX_DI_8086,
  RM_BP_SI_8086,
  RM_BP_DI_8086,
  RM_SI_8086,
  RM_DI_8086,
  RM_D16_8086,
  RM_BX_8086,

  //@NOTE(Emilio): RM = RM + (8 * MOD);
  RM_BX_SI_D8_8086,
  RM_BX_DI_D8_8086,
  RM_BP_SI_D8_8086,
  RM_BP_DI_D8_8086,
  RM_SI_D8_8086,
  RM_DI_D8_8086,
  RM_BP_D8_8086,
  RM_BX_D8_8086,

  RM_BX_SI_D16_8086,
  RM_BX_DI_D16_8086,
  RM_BP_SI_D16_8086,
  RM_BP_DI_D16_8086,
  RM_SI_D16_8086,
  RM_DI_D16_8086,
  RM_BP_D16_8086,
  RM_BX_D16_8086,

  RM_AL_MOD3_8086,
  RM_CL_MOD3_8086,
  RM_DL_MOD3_8086,
  RM_BL_MOD3_8086,
  RM_AH_MOD3_8086,
  RM_CH_MOD3_8086,
  RM_DH_MOD3_8086,
  RM_BH_MOD3_8086,

  //@NOTE(Emilio): Only if Wide Instruction
  RM_AX_MOD3_8086,
  RM_CX_MOD3_8086,
  RM_DX_MOD3_8086,
  RM_BX_MOD3_8086,
  RM_SP_MOD3_8086,
  RM_BP_MOD3_8086,
  RM_SI_MOD3_8086,
  RM_DI_MOD3_8086,

  RM_TABLE_8086_SIZE
};



#if 0
enum OP_CODES_8086
{
  MOV_RM_RM_8086,
  MOV_IMM_RM_8086,
  MOV_IMM_REG_8086,
  MOV_MEM_TO_ACC_8086,
  MOV_ACC_TO_MEM_8086,
  MOV_RM_TO_SEG_8086,
  MOV_SEG_TO_RM_8086,

  OP_CODE_8086_SIZE
};
#endif

#define EMPTY_FIELD                                 {0, 0, 0, 0}
#define OP_CODE_FIELD(_mnemonic, _opcode, _mask, _shift, _bitcount)       {_mnemonic, _opcode, _mask, _shift, _bitcount}

#define ZERO_BIT_MASK     0x0
#define SINGLE_BIT_MASK   0x1
#define TWO_BIT_MASK      0x3
#define THREE_BIT_MASK    0x7
#define FOUR_BIT_MASK     0xF
#define SIX_BIT_MASK      0x3F
#define SEVEN_BIT_MASK    0x7F
#define EIGHT_BIT_MASK    0xFF

#define FIELD_DOES_NOT_EXIST        (0 << 0)
#define FIELD_EXISTS                (1 << 0)
#define FIELD_IS_PADDING            ((1 << 1) | FIELD_DOES_NOT_EXIST)
#define FIELD_IS_IMMPLIED           ((1 << 2) | FIELD_EXISTS)
#define FIELD_IS_OPCODE_EXTENDED    ((1 << 3) | FIELD_IS_PADDING)

#define D_FIELD                                     {FIELD_EXISTS, SINGLE_BIT_MASK, 1, 0}
#define S_FIELD                                     {FIELD_EXISTS, SINGLE_BIT_MASK, 1, 0}
#define W_FIELD                                     {FIELD_EXISTS, SINGLE_BIT_MASK, 1, 0}
#define MOD_FIELD                                   {FIELD_EXISTS, TWO_BIT_MASK,    2, 0}
#define REG_FIELD                                   {FIELD_EXISTS, THREE_BIT_MASK,  3, 0}
#define RM_FIELD                                    {FIELD_EXISTS, THREE_BIT_MASK,  3, 0}
#define DATA_FIELD                                  {FIELD_EXISTS, EIGHT_BIT_MASK,  8, 0}
#define PADDING_FIELD(_bitcount)                    {FIELD_IS_PADDING, ZERO_BIT_MASK, _bitcount, 0}
#define IMMPLIED_FIELD(_num)                        {FIELD_IS_IMMPLIED,ZERO_BIT_MASK,  0, _num}
#define OPCODE_FIELD(_mask, _bitcount, _num)        {FIELD_IS_OPCODE_EXTENDED, _mask, _bitcount, _num}

//@NOTE(Emilio): mov instructions
#define OP_MOV_RM_RM    {OP_CODE_FIELD("mov", 0x22, SIX_BIT_MASK,   2, 6), D_FIELD, W_FIELD, EMPTY_FIELD, MOD_FIELD, REG_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_MOV_IMM_RM   {OP_CODE_FIELD("mov", 0x63, SEVEN_BIT_MASK, 1, 7), EMPTY_FIELD, W_FIELD, EMPTY_FIELD, MOD_FIELD, PADDING_FIELD(3), RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_MOV_IMM_REG  {OP_CODE_FIELD("mov", 0x0B, FOUR_BIT_MASK,  4, 4), EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, REG_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_MOV_MEM_ACC  {OP_CODE_FIELD("mov", 0x50, SEVEN_BIT_MASK, 1, 7), IMMPLIED_FIELD(1), W_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_MOV_ACC_MEM  {OP_CODE_FIELD("mov", 0x51, SEVEN_BIT_MASK, 1, 7), EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): add instructions
#define OP_ADD_RM_RM    {OP_CODE_FIELD("add", 0x00, SIX_BIT_MASK,   2, 6), D_FIELD, W_FIELD, EMPTY_FIELD, MOD_FIELD, REG_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_ADD_IMM_RM   {OP_CODE_FIELD("add", 0x20, SIX_BIT_MASK,   2, 6), EMPTY_FIELD, W_FIELD, S_FIELD, MOD_FIELD, OPCODE_FIELD(THREE_BIT_MASK,  3, 0x0), RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_ADD_IMM_ACC  {OP_CODE_FIELD("add", 0x02, SEVEN_BIT_MASK, 1, 7), EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): sub instructions
#define OP_SUB_RM_RM    {OP_CODE_FIELD("sub", 0x0A, SIX_BIT_MASK,   2, 6), D_FIELD, W_FIELD, EMPTY_FIELD, MOD_FIELD, REG_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_SUB_IMM_RM   {OP_CODE_FIELD("sub", 0x20, SIX_BIT_MASK,   2, 6), EMPTY_FIELD, W_FIELD, S_FIELD, MOD_FIELD, OPCODE_FIELD(THREE_BIT_MASK,  3, 0x5), RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_SUB_IMM_ACC  {OP_CODE_FIELD("sub", 0x16, SEVEN_BIT_MASK, 1, 7), EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): cmp instructions
#define OP_CMP_RM_RM    {OP_CODE_FIELD("cmp", 0x0E, SIX_BIT_MASK,   2, 6), D_FIELD, W_FIELD, EMPTY_FIELD, MOD_FIELD, REG_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_IMM_RM   {OP_CODE_FIELD("cmp", 0x20, SIX_BIT_MASK,   2, 6), EMPTY_FIELD, W_FIELD, S_FIELD, MOD_FIELD, OPCODE_FIELD(THREE_BIT_MASK,  3, 0x7), RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_CMP_IMM_ACC  {OP_CODE_FIELD("cmp", 0x1E, SEVEN_BIT_MASK, 1, 7), EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}



#endif /* _8086_CPU_H_ */
