#if !defined(_8086_CPU_H_)
#define _8086_CPU_H_

enum OP_CODE_TABLE_8086
{
  //@NOTE(Emilio): mov instructions
  MOV_RM_RM_8086,
  MOV_IMM_RM_8086,
  MOV_IMM_REG_8086,
  MOV_MEM_ACC_8086,
  MOV_ACC_MEM_8086,
  MOV_RM_SEG_8086,
  MOV_SEG_RM_8086,

  //@NOTE(Emilio): push instructions
  PUSH_RM_8086,
  PUSH_REG_8086,
  PUSH_SEG_8086,

  //@NOTE(Emilio): pop instructions
  POP_RM_8086,
  POP_REG_8086,
  POP_SEG_8086,

  //@NOTE(Emilio): xchg instructions
  XCHG_RM_REG_8086,
  XCHG_REG_ACC_8086,

  //@NOTE(Emilio): in instructions
  IN_8086,
  IN_VAR_8086,

  //@NOTE(Emilio): out instructions
  OUT_8086,
  OUT_VAR_8086,

  //@NOTE(Emilio): common instructions
  XLAT_8086,
  LEA_8086,
  LDS_8086,
  LES_8086,
  LAHF_8086,
  SAHF_8086,
  PUSHF_8086,
  POPF_8086,

  //@NOTE(Emilio): add instructions
  ADD_RM_RM_8086,
  ADD_IMM_RM_8086,
  ADD_IMM_ACC_8086,

  //@NOTE(Emilio): adc instructions
  ADC_RM_RM_8086,
  ADC_IMM_RM_8086,
  ADC_IMM_ACC_8086,

  //@NOTE(Emilio): inc instructions
  INC_RM_8086,
  INC_REG_8086,
  INC_AAA_8086,
  INC_DAA_8086,

  //@NOTE(Emilio): sub instructions
  SUB_RM_RM_8086,
  SUB_IMM_RM_8086,
  SUB_IMM_ACC_8086,

  //@NOTE(Emilio): sbb instructions
  SBB_RM_RM_8086,
  SBB_IMM_RM_8086,
  SBB_IMM_ACC_8086,

  //@NOTE(Emilio): dec instructions
  DEC_RM_8086,
  DEC_REG_8086,
  DEC_NEG_8086,

  //@NOTE(Emilio): cmp instructions
  CMP_RM_RM_8086,
  CMP_IMM_RM_8086,
  CMP_IMM_ACC_8086,
  CMP_AAS_8086,
  CMP_DAS_8086,
  CMP_MUL_8086,
  CMP_IMUL_8086,
  CMP_AAM_8086,
  CMP_DIV_8086,
  CMP_IDIV_8086,
  CMP_AAD_8086,
  CMP_CBW_8086,
  CMP_CWD_8086,

  //@NOTE(Emilio): logic instructions
  NOT_8086,
  SHL_SAL_8086,
  SHR_8086,
  SAR_8086,
  ROL_8086,
  ROR_8086,
  RCL_8086,
  RCR_8086,

  //@NOTE(Emilio): and instructions
  AND_RM_RM_8086,
  AND_IMM_RM_8086,
  AND_IMM_ACC_8086,

  //@NOTE(Emilio): test instructions
  TEST_RM_RM_8086,
  TEST_IMM_RM_8086,
  TEST_IMM_ACC_8086,

  //@NOTE(Emilio): or instructions
  OR_RM_RM_8086,
  OR_IMM_RM_8086,
  OR_IMM_ACC_8086,

  //@NOTE(Emilio): xor instructions
  XOR_RM_RM_8086,
  XOR_IMM_RM_8086,
  XOR_IMM_ACC_8086,

  //@NOTE(Emilio): string instructions
  REP_8086,
  MOVS_8086,
  CMPS_8086,
  SCAS_8086,
  LODS_8086,
  STOS_8086,

  //@NOTE(Emilio): control instructions
  CALL_DIRECT_8086,
  CALL_INDIRECT_8086,
  CALL_DIRECT_INTERSEG_8086,
  CALL_INDIRECT_INTERSEG_8086,

  //@NOTE(Emilio): ret instructions
  RET_8086,
  RET_IMM_SP_8086,
  RET_INTERSEG_8086,
  RET_INTERSEG_SP_8086,

  //@NOTE(Emilio): jmp instructions
  JMP_SEG_8086,
  JMP_SEG_SHORT_8086,
  JMP_INDIRECT_SEG_8086,
  JMP_DIRECT_INTERSEG_8086,
  JMP_INDIRECT_INTERSEG_8086,
  JMP_JE_JZ_8086,
  JMP_JL_JNGE_8086,
  JMP_JLE_JNG_8086,
  JMP_JB_JNAE_8086,
  JMP_JBE_JNA_8086,
  JMP_JP_JPE_8086,
  JMP_JO_8086,
  JMP_JS_8086,
  JMP_JNE_JNZ_8086,
  JMP_JNL_JGE_8086,
  JMP_JNLE_JG_8086,
  JMP_JNB_JAE_8086,
  JMP_JNBE_JA_8086,
  JMP_JNP_JPO_8086,
  JMP_JNO_8086,
  JMP_JNS_8086,
  JMP_LOOP_8086,
  JMP_LOOPZ_LOOPE_8086,
  JMP_LOOPNZ_LOOPN_8086,
  JMP_JCXZ_8086,

  //@NOTE(Emilio): int instructions
  INT_8086,
  INT_3_8086,
  INT_INTO_8086,
  INT_IRET_8086,

  //@NOTE(Emilio): processor control instructions
  CLC_8086,
  CMC_8086,
  STC_8086,
  CLD_8086,
  STD_8086,
  CLI_8086,
  STI_8086,
  HLT_8086,
  WAIT_8086,
//  ESC_8086,
  LOCK_8086,
  SEGMENT_8086,

  OP_CODE_TABLE_8086_SIZE
};

enum REG_TABLE_8086
{
  REG_AL_8086,
  REG_CL_8086,
  REG_DL_8086,
  REG_BL_8086,
  REG_AH_8086,
  REG_CH_8086,
  REG_DH_8086,
  REG_BH_8086,

  //@NOTE(Emilio): (REG % 8) + 8
  REG_AX_8086,
  REG_CX_8086,
  REG_DX_8086,
  REG_BX_8086,
  REG_SP_8086,
  REG_BP_8086,
  REG_SI_8086,
  REG_DI_8086,

  REG_TABLE_8086_SIZE
};

enum SEG_TABLE_8086
{
  SEG_ES_8086,
  SEG_CS_8086,
  SEG_SS_8086,
  SEG_DS_8086,

  SEG_TABLE_8086_SIZE
};

enum RM_TABLE_8086
{
  RM_BX_SI_8086,
  RM_BX_DI_8086,
  RM_BP_SI_8086,
  RM_BP_DI_8086,
  RM_SI_8086,
  RM_DI_8086,
  RM_D16_8086,
  RM_BX_8086,

  //@NOTE(Emilio): RM = RM + (8 * MOD);
  RM_BX_SI_D8_8086,
  RM_BX_DI_D8_8086,
  RM_BP_SI_D8_8086,
  RM_BP_DI_D8_8086,
  RM_SI_D8_8086,
  RM_DI_D8_8086,
  RM_BP_D8_8086,
  RM_BX_D8_8086,

  RM_BX_SI_D16_8086,
  RM_BX_DI_D16_8086,
  RM_BP_SI_D16_8086,
  RM_BP_DI_D16_8086,
  RM_SI_D16_8086,
  RM_DI_D16_8086,
  RM_BP_D16_8086,
  RM_BX_D16_8086,

  RM_AL_MOD3_8086,
  RM_CL_MOD3_8086,
  RM_DL_MOD3_8086,
  RM_BL_MOD3_8086,
  RM_AH_MOD3_8086,
  RM_CH_MOD3_8086,
  RM_DH_MOD3_8086,
  RM_BH_MOD3_8086,

  //@NOTE(Emilio): Only if Wide Instruction
  RM_AX_MOD3_8086,
  RM_CX_MOD3_8086,
  RM_DX_MOD3_8086,
  RM_BX_MOD3_8086,
  RM_SP_MOD3_8086,
  RM_BP_MOD3_8086,
  RM_SI_MOD3_8086,
  RM_DI_MOD3_8086,

  RM_TABLE_8086_SIZE
};


#define OPCODE_HAS_ZERO_FIELDS                      (1 << 0)
#define OPCODE_ONLY_PRINT_OP                        ((1 << 1) | OPCODE_HAS_ZERO_FIELDS)
#define OPCODE_IS_16BIT                             ((1 << 2) | OPCODE_ONLY_PRINT_OP)

#define ZERO_BIT_MASK                               0x0
#define SINGLE_BIT_MASK                             0x1
#define TWO_BIT_MASK                                0x3
#define THREE_BIT_MASK                              0x7
#define FOUR_BIT_MASK                               0xF
#define FIVE_BIT_MASK                               0x1F
#define SIX_BIT_MASK                                0x3F
#define SEVEN_BIT_MASK                              0x7F
#define EIGHT_BIT_MASK                              0xFF
#define SIXTEEN_BIT_MASK                            0xFFFF

//@NOTE(Emilio): Shorthand for commond definitions that are generated for
//  plex decoder_opcode_stats see 8086_decoder.h
//  and decoded as [REAL_OPCODE = ((OpCode >> Shift) & Mask)]
//  values are                    OpCode_Mask,   OpCode_Shift, OpCount_BitCount
#define DECODER_COMMON_STATS_0    ZERO_BIT_MASK,          0,          0
#define DECODER_COMMON_STATS_1    SINGLE_BIT_MASK,        7,          1
#define DECODER_COMMON_STATS_2    TWO_BIT_MASK,           6,          2
#define DECODER_COMMON_STATS_3    THREE_BIT_MASK,         5,          3
#define DECODER_COMMON_STATS_4    FOUR_BIT_MASK,          4,          4
#define DECODER_COMMON_STATS_5    FIVE_BIT_MASK,          3,          5
#define DECODER_COMMON_STATS_6    SIX_BIT_MASK,           2,          6
#define DECODER_COMMON_STATS_7    SEVEN_BIT_MASK,         1,          7
#define DECODER_COMMON_STATS_8    EIGHT_BIT_MASK,         0,          8
#define DECODER_COMMON_STATS_16   SIXTEEN_BIT_MASK,       0,          16

//@NOTE(Emilio): Shorthand for commond definitions that are generated for fields
//  values are                    OpCode_Mask,    OpCount_BitCount
#define FIELD_COMMON_STATS_0    ZERO_BIT_MASK,         0
#define FIELD_COMMON_STATS_1    SINGLE_BIT_MASK,       1
#define FIELD_COMMON_STATS_2    TWO_BIT_MASK,          2
#define FIELD_COMMON_STATS_3    THREE_BIT_MASK,        3
#define FIELD_COMMON_STATS_4    FOUR_BIT_MASK,         4
#define FIELD_COMMON_STATS_5    FIVE_BIT_MASK,         5
#define FIELD_COMMON_STATS_6    SIX_BIT_MASK,          6
#define FIELD_COMMON_STATS_7    SEVEN_BIT_MASK,        7
#define FIELD_COMMON_STATS_8    EIGHT_BIT_MASK,        8


#define FIELD_DOES_NOT_EXIST        (0 << 0)
#define FIELD_EXISTS                (1 << 0)
#define FIELD_IS_PADDING            ((1 << 1) | FIELD_DOES_NOT_EXIST)
#define FIELD_IS_IMMPLIED           ((1 << 2) | FIELD_EXISTS)
#define FIELD_IS_OPCODE_EXTENDED    ((1 << 3) | FIELD_IS_PADDING)
//@NOTE(Emilio): Jump Data gets the String $+ and have a +2 offset
#define FIELD_IS_JMP_DATA           ((1 << 4) | FIELD_EXISTS)
#define FIELD_IS_EXPLICITLY_16BITS  ((1 << 5) | FIELD_EXISTS)
#define FIELD_IS_PORT_DATA          ((1 << 6) | FIELD_EXISTS)
//@NOTE(Emilio): Logical data ALWAYS uses 'word/byte' before the operands
#define FIELD_IS_LOGIC_DATA         ((1 << 7) | FIELD_EXISTS)
#define FIELD_IS_UNSIGNED_DATA      ((1 << 8) | FIELD_IS_LOGIC_DATA)
#define FIELD_IS_UNSIGNED_TEST_DATA ((1 << 9) | FIELD_EXISTS)
#define EMPTY_FIELD                 {0, 0, 0, 0}


#define OP_CODE_FIELD(_mnemonic, _opcode, ...)       {_mnemonic, 0, _opcode, __VA_ARGS__}

#if 1
#define OP_CODE_JMP_FIELD(_mnemonic, _opcode)  {_mnemonic, OPCODE_HAS_ZERO_FIELDS, _opcode, DECODER_COMMON_STATS_8}
#define OP_CODE_ONLY_FIELD(_mnemonic, _opcode) {_mnemonic, OPCODE_ONLY_PRINT_OP, _opcode, DECODER_COMMON_STATS_8}
#define OP_CODE_16_FIELD(_mnemonic, _opcode)   {_mnemonic, OPCODE_IS_16BIT, _opcode, DECODER_COMMON_STATS_16}
#else
//@NOTE(Emilio): There are only a few instances where this macro would apply as is.
//  In reality most of the instruction have the same bit count and mask. So we should
//  split this into seperate macros, as is the case in the #if 1
//#define OPCODE_ZERO_FIELDS(_mnemonic, _opcode, _mask, _shift, _bitcount)  {_mnemonic, OPCODE_HAS_ZERO_FEILDS, _opcode, _mask, _shift, _bitcount}

//@NOTE(Emilio): This might not be need yet since the data field already describes if we want 8 bits or 16bits of data or 0bits of data.
//#define OPCODE_SINGLE_BYTE_NODATA_FIELD(_mnemonic, _opcode, _mask, _shift, _bitcount)  {_mnemonic, OPCODE_IS_SINGLE_BYTE, _opcode, _mask, _shift, _bitcount}(_mask, _bitcount, _num)
//#define OPCODE_SINGLE_BYTE_DATA_FIELD(_mnemonic, _opcode, _mask, _shift, _bitcount)    {_mnemonic, OPCODE_IS_SINGLE_BYTE, _opcode, _mask, _shift, _bitcount}(_mask, _bitcount, _num)
#endif /* @NOTE(Emilio): Just to express note above */

#define D_FIELD                                               {FIELD_EXISTS,      FIELD_COMMON_STATS_1}
#define S_FIELD                                               {FIELD_EXISTS,      FIELD_COMMON_STATS_1}
#define W_FIELD                                               {FIELD_EXISTS,      FIELD_COMMON_STATS_1}
#define ROTATE_FIELD                                          {FIELD_EXISTS,      FIELD_COMMON_STATS_1}
#define ZERO_FIELD                                            {FIELD_EXISTS,      FIELD_COMMON_STATS_1}
#define MOD_FIELD                                             {FIELD_EXISTS,      FIELD_COMMON_STATS_2}
#define REG_FIELD                                             {FIELD_EXISTS,      FIELD_COMMON_STATS_3}
#define SEG_FIELD                                             {FIELD_EXISTS,      FIELD_COMMON_STATS_2}
#define RM_FIELD                                              {FIELD_EXISTS,      FIELD_COMMON_STATS_3}
#define IMMPLIED_DISPLACMENT_FIELD                            {FIELD_IS_IMMPLIED, FIELD_COMMON_STATS_8}
#define DATA_FIELD                                            {FIELD_EXISTS,      FIELD_COMMON_STATS_8}
#define DATA_16_FIELD                                         {FIELD_IS_EXPLICITLY_16BITS, FIELD_COMMON_STATS_8}
#define DATA_JMP_FIELD                                        {FIELD_IS_JMP_DATA, FIELD_COMMON_STATS_8}
#define DATA_LOGIC_FIELD                                      {FIELD_IS_LOGIC_DATA, FIELD_COMMON_STATS_8}
#define DATA_UNSIGNED_FIELD                                   {FIELD_IS_UNSIGNED_DATA, FIELD_COMMON_STATS_8}
#define DATA_TEST_FIELD                                       {FIELD_IS_UNSIGNED_TEST_DATA, FIELD_COMMON_STATS_8}
#define DATA_PORT_FIELD                                       {FIELD_IS_PORT_DATA, FIELD_COMMON_STATS_8}
#define PADDING_FIELD(_bitcount)                              {FIELD_IS_PADDING,  ZERO_BIT_MASK, _bitcount, 0}
#define IMMPLIED_FIELD(_value)                                {FIELD_IS_IMMPLIED, ZERO_BIT_MASK,  0, _value}
#define OP_EXT_FIELD(_mask, _bitcount, _value)                {FIELD_IS_OPCODE_EXTENDED, _mask, _bitcount, _value}

//@NOTE(Emilio): mov instructions
#define OP_MOV_RM_RM        {OP_CODE_FIELD("mov", 0x22, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_MOV_IMM_RM       {OP_CODE_FIELD("mov", 0x63, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, PADDING_FIELD(3),EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_MOV_IMM_REG      {OP_CODE_FIELD("mov", 0x0B, DECODER_COMMON_STATS_4), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, REG_FIELD,  EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_MOV_MEM_ACC      {OP_CODE_FIELD("mov", 0x50, DECODER_COMMON_STATS_7), IMMPLIED_FIELD(1), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_DISPLACMENT_FIELD, EMPTY_FIELD}
#define OP_MOV_ACC_MEM      {OP_CODE_FIELD("mov", 0x51, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_DISPLACMENT_FIELD, EMPTY_FIELD}
#define OP_MOV_RM_SEG       {OP_CODE_FIELD("mov", 0x8E, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, PADDING_FIELD(1), SEG_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_MOV_SEG_RM       {OP_CODE_FIELD("mov", 0x8C, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, PADDING_FIELD(1), SEG_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): push instructions
#define OP_PUSH_RM          {OP_CODE_FIELD("push", 0xFF, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x6), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_PUSH_REG         {OP_CODE_FIELD("push", 0x0A, DECODER_COMMON_STATS_5), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(1), EMPTY_FIELD, REG_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_PUSH_SEG         {OP_CODE_FIELD("push", 0x0, DECODER_COMMON_STATS_3),  EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, SEG_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x6), EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): pop instructions
#define OP_POP_RM           {OP_CODE_FIELD("pop", 0x8F, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x0), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_POP_REG          {OP_CODE_FIELD("pop", 0x0B, DECODER_COMMON_STATS_5), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(1), EMPTY_FIELD, REG_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_POP_SEG          {OP_CODE_FIELD("pop", 0x0, DECODER_COMMON_STATS_3),  EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, SEG_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x7), EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): xchg instructions
#define OP_XCHG_RM_REG      {OP_CODE_FIELD("xchg", 0x43, DECODER_COMMON_STATS_7), IMMPLIED_FIELD(1), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_XCHG_REG_ACC     {OP_CODE_FIELD("xchg", 0x12, DECODER_COMMON_STATS_5), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(1), IMMPLIED_FIELD(3), REG_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): in instructions
#define OP_IN               {OP_CODE_FIELD("in", 0x72, DECODER_COMMON_STATS_7), IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_PORT_FIELD}
#define OP_IN_VAR           {OP_CODE_FIELD("in", 0x76, DECODER_COMMON_STATS_7), IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): out instructions
#define OP_OUT              {OP_CODE_FIELD("out", 0x73, DECODER_COMMON_STATS_7), IMMPLIED_FIELD(1), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_PORT_FIELD}
#define OP_OUT_VAR          {OP_CODE_FIELD("out", 0x77, DECODER_COMMON_STATS_7), IMMPLIED_FIELD(1), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): common instructions
#define OP_XLAT             {OP_CODE_ONLY_FIELD("xlat", 0xD7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_LEA              {OP_CODE_FIELD("lea", 0x8D, DECODER_COMMON_STATS_8), IMMPLIED_FIELD(1), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(1), MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_LDS              {OP_CODE_FIELD("lds", 0xC5, DECODER_COMMON_STATS_8), IMMPLIED_FIELD(1), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(1), MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_LES              {OP_CODE_FIELD("les", 0xC4, DECODER_COMMON_STATS_8), IMMPLIED_FIELD(1), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(1), MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_LAHF             {OP_CODE_ONLY_FIELD("lahf", 0x9F), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_SAHF             {OP_CODE_ONLY_FIELD("sahf", 0x9E), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_PUSHF            {OP_CODE_ONLY_FIELD("pushf", 0x9C), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_POPF             {OP_CODE_ONLY_FIELD("popf", 0x9D), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): add instructions
#define OP_ADD_RM_RM        {OP_CODE_FIELD("add", 0x00, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_ADD_IMM_RM       {OP_CODE_FIELD("add", 0x20, DECODER_COMMON_STATS_6), EMPTY_FIELD, S_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK,  3, 0x0), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_ADD_IMM_ACC      {OP_CODE_FIELD("add", 0x02, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): adc instructions
#define OP_ADC_RM_RM        {OP_CODE_FIELD("adc", 0x04, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_ADC_IMM_RM       {OP_CODE_FIELD("adc", 0x20, DECODER_COMMON_STATS_6), EMPTY_FIELD, S_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK,  3, 0x2), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_ADC_IMM_ACC      {OP_CODE_FIELD("adc", 0x0A, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): inc instructions
#define OP_INC_RM           {OP_CODE_FIELD("inc", 0x7F, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(0x7, 3, 0), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_INC_REG          {OP_CODE_FIELD("inc", 0x08, DECODER_COMMON_STATS_5), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(1), EMPTY_FIELD, REG_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_INC_AAA          {OP_CODE_ONLY_FIELD("aaa", 0x37), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_INC_DAA          {OP_CODE_ONLY_FIELD("daa", 0x27), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): sub instructions
#define OP_SUB_RM_RM        {OP_CODE_FIELD("sub", 0x0A, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_SUB_IMM_RM       {OP_CODE_FIELD("sub", 0x20, DECODER_COMMON_STATS_6), EMPTY_FIELD, S_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK,  3, 0x5), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_SUB_IMM_ACC      {OP_CODE_FIELD("sub", 0x16, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): sbb instructions
#define OP_SBB_RM_RM        {OP_CODE_FIELD("sbb", 0x06, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_SBB_IMM_RM       {OP_CODE_FIELD("sbb", 0x20, DECODER_COMMON_STATS_6), EMPTY_FIELD, S_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK,  3, 0x3), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_SBB_IMM_ACC      {OP_CODE_FIELD("sbb", 0x0E, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): dec instructions
#define OP_DEC_RM           {OP_CODE_FIELD("dec", 0x7F, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x1), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_DEC_REG          {OP_CODE_FIELD("dec", 0x09, DECODER_COMMON_STATS_5), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(1), EMPTY_FIELD, REG_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_DEC_NEG          {OP_CODE_FIELD("neg", 0x7B, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x3), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): cmp instructions
#define OP_CMP_RM_RM        {OP_CODE_FIELD("cmp", 0x0E, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_IMM_RM       {OP_CODE_FIELD("cmp", 0x20, DECODER_COMMON_STATS_6), EMPTY_FIELD, S_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK,  3, 0x7), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_CMP_IMM_ACC      {OP_CODE_FIELD("cmp", 0x1E, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_CMP_AAS          {OP_CODE_ONLY_FIELD("aas", 0x3F), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_DAS          {OP_CODE_ONLY_FIELD("das", 0x2F), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_MUL          {OP_CODE_FIELD("mul", 0x7B, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x4), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_IMUL         {OP_CODE_FIELD("imul", 0x7B, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x5), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_AAM          {OP_CODE_16_FIELD("aam", 0x0AD4), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_DIV          {OP_CODE_FIELD("div", 0x7B, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x6), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_IDIV         {OP_CODE_FIELD("idiv", 0x7B, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x7), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_AAD          {OP_CODE_16_FIELD("aad", 0x0AD5), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_CBW          {OP_CODE_ONLY_FIELD("cbw", 0x98), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMP_CWD          {OP_CODE_ONLY_FIELD("cwd", 0x99), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): logic instructions
#define OP_NOT              {OP_CODE_FIELD("not", 0x7B, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x2), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_SHL_SAL          {OP_CODE_FIELD("shl", 0x34, DECODER_COMMON_STATS_6), EMPTY_FIELD, EMPTY_FIELD, ROTATE_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x4), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_SHR              {OP_CODE_FIELD("shr", 0x34, DECODER_COMMON_STATS_6), EMPTY_FIELD, EMPTY_FIELD, ROTATE_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x5), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_SAR              {OP_CODE_FIELD("sar", 0x34, DECODER_COMMON_STATS_6), EMPTY_FIELD, EMPTY_FIELD, ROTATE_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x7), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_ROL              {OP_CODE_FIELD("rol", 0x34, DECODER_COMMON_STATS_6), EMPTY_FIELD, EMPTY_FIELD, ROTATE_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x0), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_ROR              {OP_CODE_FIELD("ror", 0x34, DECODER_COMMON_STATS_6), EMPTY_FIELD, EMPTY_FIELD, ROTATE_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x1), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_RCL              {OP_CODE_FIELD("rcl", 0x34, DECODER_COMMON_STATS_6), EMPTY_FIELD, EMPTY_FIELD, ROTATE_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x2), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_RCR              {OP_CODE_FIELD("rcr", 0x34, DECODER_COMMON_STATS_6), EMPTY_FIELD, EMPTY_FIELD, ROTATE_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x3), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): and instructions
#define OP_AND_RM_RM        {OP_CODE_FIELD("and", 0x08, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_AND_IMM_RM       {OP_CODE_FIELD("and", 0x40, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x4), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_UNSIGNED_FIELD}
#define OP_AND_IMM_ACC      {OP_CODE_FIELD("and", 0x12, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): test instructions
#define OP_TEST_RM_RM      {OP_CODE_FIELD("test", 0x21, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_TEST_IMM_RM     {OP_CODE_FIELD("test", 0x7B, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x0), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_TEST_FIELD}
#define OP_TEST_IMM_ACC    {OP_CODE_FIELD("test", 0x54, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): or instructions
#define OP_OR_RM_RM        {OP_CODE_FIELD("or", 0x02, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_OR_IMM_RM       {OP_CODE_FIELD("or", 0x40, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x1), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_UNSIGNED_FIELD}
#define OP_OR_IMM_ACC      {OP_CODE_FIELD("or", 0x06, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): xor instructions
#define OP_XOR_RM_RM        {OP_CODE_FIELD("xor", 0x0C, DECODER_COMMON_STATS_6), D_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, REG_FIELD, EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_XOR_IMM_RM       {OP_CODE_FIELD("xor", 0x40, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x6), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, DATA_UNSIGNED_FIELD}
#define OP_XOR_IMM_ACC      {OP_CODE_FIELD("xor", 0x1A, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, IMMPLIED_FIELD(0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): string instructions
#define REP_INSTRUCTION 0x79
#define OP_REP              {OP_CODE_FIELD("rep", 0x79, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, ZERO_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_MOVS             {OP_CODE_FIELD("movs", 0x52, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMPS             {OP_CODE_FIELD("cmps", 0x53, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_SCAS             {OP_CODE_FIELD("scas", 0x57, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_LODS             {OP_CODE_FIELD("lods", 0x56, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_STOS             {OP_CODE_FIELD("stos", 0x55, DECODER_COMMON_STATS_7), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, W_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): control instructions
#define OP_CALL_DIRECT            {OP_CODE_FIELD("call", 0xE8, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_CALL_INDIRECT          {OP_CODE_FIELD("call", 0xFF, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x2), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CALL_DIRECT_INTERSEG   {OP_CODE_FIELD("call", 0x9A, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_CALL_INDIRECT_INTERSEG {OP_CODE_FIELD("call", 0xFF, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x3), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}


//@NOTE(Emilio): ret instructions
#define OP_RET                    {OP_CODE_JMP_FIELD("ret", 0xC3), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_RET_IMM_SP             {OP_CODE_JMP_FIELD("ret", 0xC2), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_RET_INTERSEG           {OP_CODE_JMP_FIELD("ret", 0xCB), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_RET_INTERSEG_SP        {OP_CODE_JMP_FIELD("ret", 0xCA), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}

//@NOTE(Emilio): jmp instructions
#define OP_JMP_SEG                {OP_CODE_FIELD("jmp", 0xE9, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_JMP_SEG_SHORT          {OP_CODE_FIELD("jmp", 0xEB, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_JMP_INDIRECT_SEG       {OP_CODE_FIELD("jmp", 0xFF, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x4), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_JMP_DIRECT_INTERSEG    {OP_CODE_FIELD("jmp", 0xEA, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_JMP_INDIRECT_INTERSEG  {OP_CODE_FIELD("jmp", 0xFF, DECODER_COMMON_STATS_8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x5), EMPTY_FIELD, RM_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_JE_JZ                  {OP_CODE_JMP_FIELD("je", 0x74),     EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JL_JNGE                {OP_CODE_JMP_FIELD("jl", 0x7C),     EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JLE_JNG                {OP_CODE_JMP_FIELD("jle", 0x7E),    EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JB_JNAE                {OP_CODE_JMP_FIELD("jb", 0x72),     EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JBE_JNA                {OP_CODE_JMP_FIELD("jbe", 0x76),    EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JP_JPE                 {OP_CODE_JMP_FIELD("jp", 0x7A),     EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JO                     {OP_CODE_JMP_FIELD("jo", 0x70),     EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JS                     {OP_CODE_JMP_FIELD("js", 0x78),     EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JNE_JNZ                {OP_CODE_JMP_FIELD("jnz", 0x75),    EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JNL_JGE                {OP_CODE_JMP_FIELD("jnl", 0x7D),    EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JNLE_JG                {OP_CODE_JMP_FIELD("jg", 0x7F),     EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JNB_JAE                {OP_CODE_JMP_FIELD("jnb", 0x73),    EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JNBE_JA                {OP_CODE_JMP_FIELD("ja", 0x77),     EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JNP_JPO                {OP_CODE_JMP_FIELD("jnp", 0x7B),    EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JNO                    {OP_CODE_JMP_FIELD("jno", 0x71),    EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JNS                    {OP_CODE_JMP_FIELD("jns", 0x79),    EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_LOOP                   {OP_CODE_JMP_FIELD("loop", 0xE2),   EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_LOOPZ_LOOPE            {OP_CODE_JMP_FIELD("loopz", 0xE1),  EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_LOOPNZ_LOOPNE          {OP_CODE_JMP_FIELD("loopnz", 0xE0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}
#define OP_JCXZ                   {OP_CODE_JMP_FIELD("jcxz", 0xE3),   EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_JMP_FIELD}

//@NOTE(Emilio): int instructions
#define OP_INT                    {OP_CODE_JMP_FIELD("int", 0xCD),  EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, DATA_FIELD}
#define OP_INT_3                  {OP_CODE_JMP_FIELD("int3", 0xCC), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_INTO                   {OP_CODE_JMP_FIELD("into", 0xCE), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_IRET                   {OP_CODE_JMP_FIELD("iret", 0xCF), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}

//@NOTE(Emilio): processor control instructions
#define OP_CLC                    {OP_CODE_JMP_FIELD("clc", 0xF8), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CMC                    {OP_CODE_JMP_FIELD("cmc", 0xF5), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_STC                    {OP_CODE_JMP_FIELD("stc", 0xF9), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CLD                    {OP_CODE_JMP_FIELD("cld", 0xFC), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_STD                    {OP_CODE_JMP_FIELD("std", 0xFD), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_CLI                    {OP_CODE_JMP_FIELD("cli", 0xFA), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_STI                    {OP_CODE_JMP_FIELD("sti", 0xFB), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_HLT                    {OP_CODE_JMP_FIELD("hlt", 0xF4), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define OP_WAIT                   {OP_CODE_JMP_FIELD("wait",0x9B), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
//#define OP_ESC                    {OP_CODE_FIELD("esc", 0x1B, FIVE_BIT_MASK,  3, 5), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, MOD_FIELD, EMPTY_FIELD, RM_FIELD,  EMPTY_FIELD, EMPTY_FIELD}
#define OP_LOCK                   {OP_CODE_ONLY_FIELD("lock",0xF0), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD}
#define SEG_OVERRIDE_INSTRUCTION_01 0x1
#define SEG_OVERRIDE_INSTRUCTION_02 0x6
#define OP_SEGMENT                {OP_CODE_FIELD("---", 0x01, DECODER_COMMON_STATS_3), EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, EMPTY_FIELD, SEG_FIELD, OP_EXT_FIELD(THREE_BIT_MASK, 3, 0x6), EMPTY_FIELD, EMPTY_FIELD}

#endif /* _8086_CPU_H_ */
